spring:
  datasource:
    url: jdbc:oracle:thin:@dki-oradb:1521/XEPDB1
    username: inscrip_admin
    password: admin
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

server:
  port: 9091
